--@author: yyumchi
--@date: 2025-09-04
--[[@description:
    Short description here.
]]
-----------------------------
-- VARIABLES --
-----------------------------

local Module = {}

-- CONSTANTS --

-----------------------------
-- PRIVATE FUNCTIONS --

-----------------------------
-- PUBLIC FUNCTIONS --

function Module:Init()
    -- initialization code
end

function Module:Start()
    -- start / runtime code
end

-----------------------------
--MAIN--
-----------------------------

return Module